# Generated by Django 4.2.27 on 2025-12-03 16:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Haunt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name for the haunt', max_length=200)),
                ('url', models.URLField(help_text='URL to monitor')),
                ('description', models.TextField(blank=True, help_text='Natural language description of what to monitor')),
                ('config', models.JSONField(default=dict, help_text='JSON configuration with selectors, normalization rules, and truthy values')),
                ('current_state', models.JSONField(default=dict, help_text='Current key-value state extracted from the site')),
                ('last_alert_state', models.JSONField(blank=True, help_text="State when last alert was sent (for 'once' alert mode)", null=True)),
                ('alert_mode', models.CharField(choices=[('once', 'Alert once when condition is met'), ('on_change', 'Alert on every change')], default='on_change', help_text='When to send alerts', max_length=20)),
                ('scrape_interval', models.IntegerField(choices=[(15, '15 minutes'), (30, '30 minutes'), (60, '1 hour'), (1440, '24 hours')], default=60, help_text='How often to scrape the site (in minutes)', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(1440)])),
                ('is_public', models.BooleanField(default=False, help_text='Whether this haunt is publicly visible')),
                ('public_slug', models.SlugField(blank=True, help_text='URL-friendly identifier for public access', max_length=100, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether monitoring is active')),
                ('last_scraped_at', models.DateTimeField(blank=True, help_text='When this haunt was last scraped', null=True)),
                ('last_error', models.TextField(blank=True, help_text='Last error message if scraping failed')),
                ('error_count', models.IntegerField(default=0, help_text='Consecutive error count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='haunts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Haunt',
                'verbose_name_plural': 'Haunts',
                'db_table': 'haunts_haunt',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'is_active'], name='haunts_haun_owner_i_3c1bb5_idx'), models.Index(fields=['is_public', 'public_slug'], name='haunts_haun_is_publ_c677f1_idx'), models.Index(fields=['scrape_interval', 'is_active'], name='haunts_haun_scrape__dad5fb_idx'), models.Index(fields=['last_scraped_at'], name='haunts_haun_last_sc_9a04c7_idx')],
            },
        ),
    ]
