# Generated by Django 4.2.27 on 2025-12-03 16:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('haunts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUIPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_panel_width', models.IntegerField(default=250, help_text='Width of the navigation panel in pixels', validators=[django.core.validators.MinValueValidator(200), django.core.validators.MaxValueValidator(500)])),
                ('middle_panel_width', models.IntegerField(default=400, help_text='Width of the item list panel in pixels', validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(800)])),
                ('keyboard_shortcuts_enabled', models.BooleanField(default=True, help_text='Enable keyboard shortcuts (J/K navigation, etc.)')),
                ('auto_mark_read_on_scroll', models.BooleanField(default=False, help_text='Automatically mark items as read when scrolled past')),
                ('auto_mark_read_on_open', models.BooleanField(default=True, help_text='Automatically mark items as read when opened')),
                ('collapsed_folders', models.JSONField(default=list, help_text='List of folder IDs that are collapsed in the UI')),
                ('items_per_page', models.IntegerField(default=50, help_text='Number of items to display per page', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(200)])),
                ('show_read_items', models.BooleanField(default=True, help_text='Show read items in the item list')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ui_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User UI Preferences',
                'verbose_name_plural': 'User UI Preferences',
                'db_table': 'haunts_user_ui_preferences',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Folder name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent folder for hierarchical organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='haunts.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Folder',
                'verbose_name_plural': 'Folders',
                'db_table': 'haunts_folder',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='haunt',
            name='folder',
            field=models.ForeignKey(blank=True, help_text='Folder containing this haunt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='haunts', to='haunts.folder'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['user', 'parent'], name='haunts_fold_user_id_570374_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('user', 'name', 'parent')},
        ),
    ]
