# Generated by Django 4.2.27 on 2025-12-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haunts', '0002_useruipreferences_folder_haunt_folder_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='haunt',
            index=models.Index(fields=['owner', 'folder'], name='haunts_haun_owner_i_e5ed26_idx'),
        ),
    ]
