# Generated by Django 4.2.27 on 2025-12-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haunts', '0003_haunt_haunts_haun_owner_i_e5ed26_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haunt',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='JSON configuration with selectors, normalization rules, and truthy values'),
        ),
        migrations.AlterField(
            model_name='haunt',
            name='current_state',
            field=models.JSONField(blank=True, default=dict, help_text='Current key-value state extracted from the site'),
        ),
    ]
