# Generated by Django 4.2.27 on 2025-12-04 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haunts', '0005_add_created_at_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='haunt',
            new_name='haunts_haun_created_9a3e5f_idx',
            old_name='haunts_haun_created_idx',
        ),
    ]
