# Generated by Django 4.2.27 on 2025-12-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haunts', '0007_add_enable_ai_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='haunt',
            name='alert_mode',
        ),
        migrations.AlterField(
            model_name='haunt',
            name='enable_ai_summary',
            field=models.BooleanField(default=True, help_text='Enable AI-generated summaries and alert decisions'),
        ),
    ]
