# Generated by Django 4.2.27 on 2025-12-03 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('haunts', '0003_haunt_haunts_haun_owner_i_e5ed26_idx'),
        ('rss', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the user has read this item')),
                ('is_starred', models.BooleanField(default=False, help_text='Whether the user has starred this item')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the item was marked as read', null=True)),
                ('starred_at', models.DateTimeField(blank=True, help_text='When the item was starred', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rss_item', models.ForeignKey(help_text='The RSS item this state refers to', on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='rss.rssitem')),
                ('user', models.ForeignKey(help_text='User who owns this read state', on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Read State',
                'verbose_name_plural': 'User Read States',
                'db_table': 'subscriptions_user_read_state',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='subscriptio_user_id_c6e0fa_idx'), models.Index(fields=['user', 'is_starred'], name='subscriptio_user_id_daa85e_idx'), models.Index(fields=['user', 'rss_item'], name='subscriptio_user_id_aa600a_idx'), models.Index(fields=['rss_item'], name='subscriptio_rss_ite_8dba25_idx')],
                'unique_together': {('user', 'rss_item')},
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, help_text='When the subscription was created')),
                ('notifications_enabled', models.BooleanField(default=True, help_text='Whether to receive notifications for this subscription')),
                ('haunt', models.ForeignKey(help_text='The haunt being subscribed to', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='haunts.haunt')),
                ('user', models.ForeignKey(help_text='User who subscribed to the haunt', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'subscriptions_subscription',
                'ordering': ['-subscribed_at'],
                'indexes': [models.Index(fields=['user', '-subscribed_at'], name='subscriptio_user_id_2a97dd_idx'), models.Index(fields=['haunt'], name='subscriptio_haunt_i_b3ab11_idx')],
                'unique_together': {('user', 'haunt')},
            },
        ),
    ]
