# Generated by Django 4.2.27 on 2025-12-03 16:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('haunts', '0003_haunt_haunts_haun_owner_i_e5ed26_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='RSS item title describing the change', max_length=300)),
                ('description', models.TextField(help_text='Detailed description of the change, may include AI summary')),
                ('link', models.URLField(help_text='Link to the monitored page')),
                ('guid', models.CharField(help_text='Unique identifier for RSS item', max_length=100, unique=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Publication date for RSS feed')),
                ('change_data', models.JSONField(default=dict, help_text='JSON data containing the detected changes')),
                ('ai_summary', models.TextField(blank=True, help_text='AI-generated summary of the change')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('haunt', models.ForeignKey(help_text='The haunt that generated this RSS item', on_delete=django.db.models.deletion.CASCADE, related_name='rss_items', to='haunts.haunt')),
            ],
            options={
                'verbose_name': 'RSS Item',
                'verbose_name_plural': 'RSS Items',
                'db_table': 'rss_item',
                'ordering': ['-pub_date'],
                'indexes': [models.Index(fields=['haunt', '-pub_date'], name='rss_item_haunt_i_65f33a_idx'), models.Index(fields=['pub_date'], name='rss_item_pub_dat_193079_idx'), models.Index(fields=['guid'], name='rss_item_guid_7a0ca2_idx')],
            },
        ),
    ]
